### PR TITLE
Support Nickname Change Requests

### PR DESCRIPTION
**Pull request by askvortsov1**
This also includes a variety of bugfixes. The commit history should be fairly instructive.

I'd like to follow this up with a PR that standardized naming to "name change requests" vs "username change requests" as much as possible.

### CODE REVIEW

**Review by imorland — CHANGES_REQUESTED** [review]
Thanks for the overhaul here 👍 

I gave this a quick run locally, and there appears to be a few bits and pieces to address..

- `canEditOwnNickname` does not appear to be attached to the `user`, so the conditional in `addRequestSetting.js` does not fire
- As nickname requests are to be handled via this extension, I feel we should remove the 'Change Nickname` button on the user settings page?
- Dupe translation string in permissions (I highlighted above)

**Comment by askvortsov1** [comment]
> * I feel we should remove the 'Change Nickname` button on the user settings page?

Wdym? There are 3 cases here:

- The user can edit their own nickname (via the permission from flarum/nicknames): Only the flarum/nicknames button will be shown
- The user can request nickname changes (via the permission here): Only the button here would be shown
- The user has neither permission: No buttons are shown

> canEditOwnNickname does not appear to be attached to the user, so the conditional in addRequestSetting.js does not fire

It was when I tested it

**Comment by imorland** [comment]
Looking good!

One issue I saw locally..

`username` = user2
`nickname` = user22

Requesting to change nickname to user2 does not submit a request. However, requesting to change to user222 is fine.


Comment. At first, it confused me at first that I had to change the flarum/nicknames `edit own` permission up to admin, then change fof/username-request permissions accordingly. Perhaps this could be improved in some way?

**Comment by askvortsov1** [comment]
> Comment. At first, it confused me at first that I had to change the flarum/nicknames `edit own` permission up to admin, then change fof/username-request permissions accordingly. Perhaps this could be improved in some way?

I agree that this is a bit messy, but I'm not 100% sure how it could be made better (unless we modified something in flarum/nicknames directly).

**Comment by askvortsov1** [comment]
Bump! :)

**Comment by imorland** [comment]
Oops! Sorry, I'll look at this again this evening, unless someone else beats me to it :)

**Pull request merged**
